/*
RIK API

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the FunctionWorkloadFunctionExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FunctionWorkloadFunctionExecution{}

// FunctionWorkloadFunctionExecution struct for FunctionWorkloadFunctionExecution
type FunctionWorkloadFunctionExecution struct {
	Rootfs *string `json:"rootfs,omitempty"`
}

// NewFunctionWorkloadFunctionExecution instantiates a new FunctionWorkloadFunctionExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFunctionWorkloadFunctionExecution() *FunctionWorkloadFunctionExecution {
	this := FunctionWorkloadFunctionExecution{}
	return &this
}

// NewFunctionWorkloadFunctionExecutionWithDefaults instantiates a new FunctionWorkloadFunctionExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFunctionWorkloadFunctionExecutionWithDefaults() *FunctionWorkloadFunctionExecution {
	this := FunctionWorkloadFunctionExecution{}
	return &this
}

// GetRootfs returns the Rootfs field value if set, zero value otherwise.
func (o *FunctionWorkloadFunctionExecution) GetRootfs() string {
	if o == nil || IsNil(o.Rootfs) {
		var ret string
		return ret
	}
	return *o.Rootfs
}

// GetRootfsOk returns a tuple with the Rootfs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FunctionWorkloadFunctionExecution) GetRootfsOk() (*string, bool) {
	if o == nil || IsNil(o.Rootfs) {
		return nil, false
	}
	return o.Rootfs, true
}

// HasRootfs returns a boolean if a field has been set.
func (o *FunctionWorkloadFunctionExecution) HasRootfs() bool {
	if o != nil && !IsNil(o.Rootfs) {
		return true
	}

	return false
}

// SetRootfs gets a reference to the given string and assigns it to the Rootfs field.
func (o *FunctionWorkloadFunctionExecution) SetRootfs(v string) {
	o.Rootfs = &v
}

func (o FunctionWorkloadFunctionExecution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FunctionWorkloadFunctionExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rootfs) {
		toSerialize["rootfs"] = o.Rootfs
	}
	return toSerialize, nil
}

type NullableFunctionWorkloadFunctionExecution struct {
	value *FunctionWorkloadFunctionExecution
	isSet bool
}

func (v NullableFunctionWorkloadFunctionExecution) Get() *FunctionWorkloadFunctionExecution {
	return v.value
}

func (v *NullableFunctionWorkloadFunctionExecution) Set(val *FunctionWorkloadFunctionExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableFunctionWorkloadFunctionExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableFunctionWorkloadFunctionExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFunctionWorkloadFunctionExecution(val *FunctionWorkloadFunctionExecution) *NullableFunctionWorkloadFunctionExecution {
	return &NullableFunctionWorkloadFunctionExecution{value: val, isSet: true}
}

func (v NullableFunctionWorkloadFunctionExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFunctionWorkloadFunctionExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


