/*
RIK

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetWorkloadsResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWorkloadsResponseInner{}

// GetWorkloadsResponseInner struct for GetWorkloadsResponseInner
type GetWorkloadsResponseInner struct {
	// Simple helper schema to define an UUID
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Value *Workload `json:"value,omitempty"`
}

// NewGetWorkloadsResponseInner instantiates a new GetWorkloadsResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkloadsResponseInner() *GetWorkloadsResponseInner {
	this := GetWorkloadsResponseInner{}
	return &this
}

// NewGetWorkloadsResponseInnerWithDefaults instantiates a new GetWorkloadsResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkloadsResponseInnerWithDefaults() *GetWorkloadsResponseInner {
	this := GetWorkloadsResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetWorkloadsResponseInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkloadsResponseInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetWorkloadsResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetWorkloadsResponseInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetWorkloadsResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkloadsResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetWorkloadsResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetWorkloadsResponseInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetWorkloadsResponseInner) GetValue() Workload {
	if o == nil || IsNil(o.Value) {
		var ret Workload
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkloadsResponseInner) GetValueOk() (*Workload, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetWorkloadsResponseInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given Workload and assigns it to the Value field.
func (o *GetWorkloadsResponseInner) SetValue(v Workload) {
	o.Value = &v
}

func (o GetWorkloadsResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWorkloadsResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableGetWorkloadsResponseInner struct {
	value *GetWorkloadsResponseInner
	isSet bool
}

func (v NullableGetWorkloadsResponseInner) Get() *GetWorkloadsResponseInner {
	return v.value
}

func (v *NullableGetWorkloadsResponseInner) Set(val *GetWorkloadsResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkloadsResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkloadsResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkloadsResponseInner(val *GetWorkloadsResponseInner) *NullableGetWorkloadsResponseInner {
	return &NullableGetWorkloadsResponseInner{value: val, isSet: true}
}

func (v NullableGetWorkloadsResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkloadsResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


