/*
RIK

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetInstancesResponseInnerAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInstancesResponseInnerAllOf{}

// GetInstancesResponseInnerAllOf struct for GetInstancesResponseInnerAllOf
type GetInstancesResponseInnerAllOf struct {
	Value *Instance `json:"value,omitempty"`
}

// NewGetInstancesResponseInnerAllOf instantiates a new GetInstancesResponseInnerAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInstancesResponseInnerAllOf() *GetInstancesResponseInnerAllOf {
	this := GetInstancesResponseInnerAllOf{}
	return &this
}

// NewGetInstancesResponseInnerAllOfWithDefaults instantiates a new GetInstancesResponseInnerAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInstancesResponseInnerAllOfWithDefaults() *GetInstancesResponseInnerAllOf {
	this := GetInstancesResponseInnerAllOf{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetInstancesResponseInnerAllOf) GetValue() Instance {
	if o == nil || IsNil(o.Value) {
		var ret Instance
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInstancesResponseInnerAllOf) GetValueOk() (*Instance, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetInstancesResponseInnerAllOf) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given Instance and assigns it to the Value field.
func (o *GetInstancesResponseInnerAllOf) SetValue(v Instance) {
	o.Value = &v
}

func (o GetInstancesResponseInnerAllOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInstancesResponseInnerAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableGetInstancesResponseInnerAllOf struct {
	value *GetInstancesResponseInnerAllOf
	isSet bool
}

func (v NullableGetInstancesResponseInnerAllOf) Get() *GetInstancesResponseInnerAllOf {
	return v.value
}

func (v *NullableGetInstancesResponseInnerAllOf) Set(val *GetInstancesResponseInnerAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInstancesResponseInnerAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInstancesResponseInnerAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInstancesResponseInnerAllOf(val *GetInstancesResponseInnerAllOf) *NullableGetInstancesResponseInnerAllOf {
	return &NullableGetInstancesResponseInnerAllOf{value: val, isSet: true}
}

func (v NullableGetInstancesResponseInnerAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInstancesResponseInnerAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


