/*
RIK

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetInstances200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInstances200Response{}

// GetInstances200Response struct for GetInstances200Response
type GetInstances200Response struct {
	Instances [][]GetInstancesResponseInner `json:"instances,omitempty"`
}

// NewGetInstances200Response instantiates a new GetInstances200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInstances200Response() *GetInstances200Response {
	this := GetInstances200Response{}
	return &this
}

// NewGetInstances200ResponseWithDefaults instantiates a new GetInstances200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInstances200ResponseWithDefaults() *GetInstances200Response {
	this := GetInstances200Response{}
	return &this
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *GetInstances200Response) GetInstances() [][]GetInstancesResponseInner {
	if o == nil || IsNil(o.Instances) {
		var ret [][]GetInstancesResponseInner
		return ret
	}
	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInstances200Response) GetInstancesOk() ([][]GetInstancesResponseInner, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *GetInstances200Response) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given [][]GetInstancesResponseInner and assigns it to the Instances field.
func (o *GetInstances200Response) SetInstances(v [][]GetInstancesResponseInner) {
	o.Instances = v
}

func (o GetInstances200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInstances200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	return toSerialize, nil
}

type NullableGetInstances200Response struct {
	value *GetInstances200Response
	isSet bool
}

func (v NullableGetInstances200Response) Get() *GetInstances200Response {
	return v.value
}

func (v *NullableGetInstances200Response) Set(val *GetInstances200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInstances200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInstances200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInstances200Response(val *GetInstances200Response) *NullableGetInstances200Response {
	return &NullableGetInstances200Response{value: val, isSet: true}
}

func (v NullableGetInstances200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInstances200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


