/*
RIK API

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ContainerWorkload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerWorkload{}

// ContainerWorkload struct for ContainerWorkload
type ContainerWorkload struct {
	Containers []ContainerWorkloadContainersInner `json:"containers,omitempty"`
}

// NewContainerWorkload instantiates a new ContainerWorkload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerWorkload() *ContainerWorkload {
	this := ContainerWorkload{}
	return &this
}

// NewContainerWorkloadWithDefaults instantiates a new ContainerWorkload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerWorkloadWithDefaults() *ContainerWorkload {
	this := ContainerWorkload{}
	return &this
}

// GetContainers returns the Containers field value if set, zero value otherwise.
func (o *ContainerWorkload) GetContainers() []ContainerWorkloadContainersInner {
	if o == nil || IsNil(o.Containers) {
		var ret []ContainerWorkloadContainersInner
		return ret
	}
	return o.Containers
}

// GetContainersOk returns a tuple with the Containers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContainerWorkload) GetContainersOk() ([]ContainerWorkloadContainersInner, bool) {
	if o == nil || IsNil(o.Containers) {
		return nil, false
	}
	return o.Containers, true
}

// HasContainers returns a boolean if a field has been set.
func (o *ContainerWorkload) HasContainers() bool {
	if o != nil && !IsNil(o.Containers) {
		return true
	}

	return false
}

// SetContainers gets a reference to the given []ContainerWorkloadContainersInner and assigns it to the Containers field.
func (o *ContainerWorkload) SetContainers(v []ContainerWorkloadContainersInner) {
	o.Containers = v
}

func (o ContainerWorkload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerWorkload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Containers) {
		toSerialize["containers"] = o.Containers
	}
	return toSerialize, nil
}

type NullableContainerWorkload struct {
	value *ContainerWorkload
	isSet bool
}

func (v NullableContainerWorkload) Get() *ContainerWorkload {
	return v.value
}

func (v *NullableContainerWorkload) Set(val *ContainerWorkload) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerWorkload) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerWorkload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerWorkload(val *ContainerWorkload) *NullableContainerWorkload {
	return &NullableContainerWorkload{value: val, isSet: true}
}

func (v NullableContainerWorkload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerWorkload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


