/*
RIK API

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetWorkloadInstancesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWorkloadInstancesResponse{}

// GetWorkloadInstancesResponse struct for GetWorkloadInstancesResponse
type GetWorkloadInstancesResponse struct {
	Instances []Instance `json:"instances,omitempty"`
}

// NewGetWorkloadInstancesResponse instantiates a new GetWorkloadInstancesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkloadInstancesResponse() *GetWorkloadInstancesResponse {
	this := GetWorkloadInstancesResponse{}
	return &this
}

// NewGetWorkloadInstancesResponseWithDefaults instantiates a new GetWorkloadInstancesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkloadInstancesResponseWithDefaults() *GetWorkloadInstancesResponse {
	this := GetWorkloadInstancesResponse{}
	return &this
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *GetWorkloadInstancesResponse) GetInstances() []Instance {
	if o == nil || IsNil(o.Instances) {
		var ret []Instance
		return ret
	}
	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkloadInstancesResponse) GetInstancesOk() ([]Instance, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *GetWorkloadInstancesResponse) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []Instance and assigns it to the Instances field.
func (o *GetWorkloadInstancesResponse) SetInstances(v []Instance) {
	o.Instances = v
}

func (o GetWorkloadInstancesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWorkloadInstancesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	return toSerialize, nil
}

type NullableGetWorkloadInstancesResponse struct {
	value *GetWorkloadInstancesResponse
	isSet bool
}

func (v NullableGetWorkloadInstancesResponse) Get() *GetWorkloadInstancesResponse {
	return v.value
}

func (v *NullableGetWorkloadInstancesResponse) Set(val *GetWorkloadInstancesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkloadInstancesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkloadInstancesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkloadInstancesResponse(val *GetWorkloadInstancesResponse) *NullableGetWorkloadInstancesResponse {
	return &NullableGetWorkloadInstancesResponse{value: val, isSet: true}
}

func (v NullableGetWorkloadInstancesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkloadInstancesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


