/*
RIK API

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the ApiV0WorkloadsInstancesWorkloadIdGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV0WorkloadsInstancesWorkloadIdGet200Response{}

// ApiV0WorkloadsInstancesWorkloadIdGet200Response struct for ApiV0WorkloadsInstancesWorkloadIdGet200Response
type ApiV0WorkloadsInstancesWorkloadIdGet200Response struct {
	Instances []Instance `json:"instances,omitempty"`
}

// NewApiV0WorkloadsInstancesWorkloadIdGet200Response instantiates a new ApiV0WorkloadsInstancesWorkloadIdGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV0WorkloadsInstancesWorkloadIdGet200Response() *ApiV0WorkloadsInstancesWorkloadIdGet200Response {
	this := ApiV0WorkloadsInstancesWorkloadIdGet200Response{}
	return &this
}

// NewApiV0WorkloadsInstancesWorkloadIdGet200ResponseWithDefaults instantiates a new ApiV0WorkloadsInstancesWorkloadIdGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV0WorkloadsInstancesWorkloadIdGet200ResponseWithDefaults() *ApiV0WorkloadsInstancesWorkloadIdGet200Response {
	this := ApiV0WorkloadsInstancesWorkloadIdGet200Response{}
	return &this
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *ApiV0WorkloadsInstancesWorkloadIdGet200Response) GetInstances() []Instance {
	if o == nil || IsNil(o.Instances) {
		var ret []Instance
		return ret
	}
	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV0WorkloadsInstancesWorkloadIdGet200Response) GetInstancesOk() ([]Instance, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *ApiV0WorkloadsInstancesWorkloadIdGet200Response) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []Instance and assigns it to the Instances field.
func (o *ApiV0WorkloadsInstancesWorkloadIdGet200Response) SetInstances(v []Instance) {
	o.Instances = v
}

func (o ApiV0WorkloadsInstancesWorkloadIdGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV0WorkloadsInstancesWorkloadIdGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	return toSerialize, nil
}

type NullableApiV0WorkloadsInstancesWorkloadIdGet200Response struct {
	value *ApiV0WorkloadsInstancesWorkloadIdGet200Response
	isSet bool
}

func (v NullableApiV0WorkloadsInstancesWorkloadIdGet200Response) Get() *ApiV0WorkloadsInstancesWorkloadIdGet200Response {
	return v.value
}

func (v *NullableApiV0WorkloadsInstancesWorkloadIdGet200Response) Set(val *ApiV0WorkloadsInstancesWorkloadIdGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV0WorkloadsInstancesWorkloadIdGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV0WorkloadsInstancesWorkloadIdGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV0WorkloadsInstancesWorkloadIdGet200Response(val *ApiV0WorkloadsInstancesWorkloadIdGet200Response) *NullableApiV0WorkloadsInstancesWorkloadIdGet200Response {
	return &NullableApiV0WorkloadsInstancesWorkloadIdGet200Response{value: val, isSet: true}
}

func (v NullableApiV0WorkloadsInstancesWorkloadIdGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV0WorkloadsInstancesWorkloadIdGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


