/*
RIK API

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the GetWorkloadInstances200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWorkloadInstances200Response{}

// GetWorkloadInstances200Response struct for GetWorkloadInstances200Response
type GetWorkloadInstances200Response struct {
	Instances []Instance `json:"instances,omitempty"`
}

// NewGetWorkloadInstances200Response instantiates a new GetWorkloadInstances200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkloadInstances200Response() *GetWorkloadInstances200Response {
	this := GetWorkloadInstances200Response{}
	return &this
}

// NewGetWorkloadInstances200ResponseWithDefaults instantiates a new GetWorkloadInstances200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkloadInstances200ResponseWithDefaults() *GetWorkloadInstances200Response {
	this := GetWorkloadInstances200Response{}
	return &this
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *GetWorkloadInstances200Response) GetInstances() []Instance {
	if o == nil || IsNil(o.Instances) {
		var ret []Instance
		return ret
	}
	return o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkloadInstances200Response) GetInstancesOk() ([]Instance, bool) {
	if o == nil || IsNil(o.Instances) {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *GetWorkloadInstances200Response) HasInstances() bool {
	if o != nil && !IsNil(o.Instances) {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []Instance and assigns it to the Instances field.
func (o *GetWorkloadInstances200Response) SetInstances(v []Instance) {
	o.Instances = v
}

func (o GetWorkloadInstances200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWorkloadInstances200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Instances) {
		toSerialize["instances"] = o.Instances
	}
	return toSerialize, nil
}

type NullableGetWorkloadInstances200Response struct {
	value *GetWorkloadInstances200Response
	isSet bool
}

func (v NullableGetWorkloadInstances200Response) Get() *GetWorkloadInstances200Response {
	return v.value
}

func (v *NullableGetWorkloadInstances200Response) Set(val *GetWorkloadInstances200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkloadInstances200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkloadInstances200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkloadInstances200Response(val *GetWorkloadInstances200Response) *NullableGetWorkloadInstances200Response {
	return &NullableGetWorkloadInstances200Response{value: val, isSet: true}
}

func (v NullableGetWorkloadInstances200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkloadInstances200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


