/*
RIK API

RESTful public-facing API. The API is accessible through HTTP calls on specific URLs carrying JSON modeled data. 

API version: 0.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// checks if the InstanceSpecFunctionExecution type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InstanceSpecFunctionExecution{}

// InstanceSpecFunctionExecution struct for InstanceSpecFunctionExecution
type InstanceSpecFunctionExecution struct {
	Rootfs *string `json:"rootfs,omitempty"`
}

// NewInstanceSpecFunctionExecution instantiates a new InstanceSpecFunctionExecution object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstanceSpecFunctionExecution() *InstanceSpecFunctionExecution {
	this := InstanceSpecFunctionExecution{}
	return &this
}

// NewInstanceSpecFunctionExecutionWithDefaults instantiates a new InstanceSpecFunctionExecution object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstanceSpecFunctionExecutionWithDefaults() *InstanceSpecFunctionExecution {
	this := InstanceSpecFunctionExecution{}
	return &this
}

// GetRootfs returns the Rootfs field value if set, zero value otherwise.
func (o *InstanceSpecFunctionExecution) GetRootfs() string {
	if o == nil || IsNil(o.Rootfs) {
		var ret string
		return ret
	}
	return *o.Rootfs
}

// GetRootfsOk returns a tuple with the Rootfs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InstanceSpecFunctionExecution) GetRootfsOk() (*string, bool) {
	if o == nil || IsNil(o.Rootfs) {
		return nil, false
	}
	return o.Rootfs, true
}

// HasRootfs returns a boolean if a field has been set.
func (o *InstanceSpecFunctionExecution) HasRootfs() bool {
	if o != nil && !IsNil(o.Rootfs) {
		return true
	}

	return false
}

// SetRootfs gets a reference to the given string and assigns it to the Rootfs field.
func (o *InstanceSpecFunctionExecution) SetRootfs(v string) {
	o.Rootfs = &v
}

func (o InstanceSpecFunctionExecution) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InstanceSpecFunctionExecution) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Rootfs) {
		toSerialize["rootfs"] = o.Rootfs
	}
	return toSerialize, nil
}

type NullableInstanceSpecFunctionExecution struct {
	value *InstanceSpecFunctionExecution
	isSet bool
}

func (v NullableInstanceSpecFunctionExecution) Get() *InstanceSpecFunctionExecution {
	return v.value
}

func (v *NullableInstanceSpecFunctionExecution) Set(val *InstanceSpecFunctionExecution) {
	v.value = val
	v.isSet = true
}

func (v NullableInstanceSpecFunctionExecution) IsSet() bool {
	return v.isSet
}

func (v *NullableInstanceSpecFunctionExecution) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstanceSpecFunctionExecution(val *InstanceSpecFunctionExecution) *NullableInstanceSpecFunctionExecution {
	return &NullableInstanceSpecFunctionExecution{value: val, isSet: true}
}

func (v NullableInstanceSpecFunctionExecution) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstanceSpecFunctionExecution) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


